import { prisma } from '../src/infrastructure/database';

async function main() {
  const testMarker = 'SENTINELAI_PERSISTENCE_SMOKE_TEST';

  console.log('Creating test incident...');

  const incident = await prisma.incident.create({
    data: {
      title: testMarker,
      description: 'Temporary persistence smoke-test incident.',
      severity: 'HIGH',
      priority: 10,
      status: 'IDENTIFIED',
      startedAt: new Date(),
    },
  });

  console.log(`Incident created: ${incident.id}`);

  const participant = await prisma.incidentParticipant.create({
    data: {
      incidentId: incident.id,
      userId: 'smoke-test-user',
      role: 'RESPONDER',
    },
  });

  console.log(`Participant created: ${participant.id}`);

  const event = await prisma.incidentEvent.create({
    data: {
      incidentId: incident.id,
      eventType: 'ALERT',
      occurredAt: new Date(),
      sequence: 1,
      title: 'Smoke-test alert',
      description: 'Temporary alert generated by persistence smoke test.',
      source: 'smoke-test',
      metadata: {
        test: true,
        marker: testMarker,
      },
    },
  });

  console.log(`Event created: ${event.id}`);

  const evidence = await prisma.evidence.create({
    data: {
      incidentId: incident.id,
      evidenceType: 'LOG',
      title: 'Smoke-test log evidence',
      description: 'Temporary evidence generated by persistence smoke test.',
      source: 'smoke-test',
      sourceRef: 'smoke-test-ref',
      collectedAt: new Date(),
      occurredAt: new Date(),
      contentHash: 'smoke-test-hash',
      trustLevel: 'HIGH',
      metadata: {
        test: true,
        marker: testMarker,
      },
    },
  });

  console.log(`Evidence created: ${evidence.id}`);

  const investigation = await prisma.investigation.create({
    data: {
      incidentId: incident.id,
      summary: 'Temporary smoke-test investigation.',
      startedAt: new Date(),
    },
  });

  console.log(`Investigation created: ${investigation.id}`);

  console.log('\nReading complete relation graph...');

  const persisted = await prisma.incident.findUnique({
    where: {
      id: incident.id,
    },
    include: {
      participants: true,
      events: true,
      evidence: true,
      investigation: true,
    },
  });

  if (!persisted) {
    throw new Error('Smoke-test incident could not be read back.');
  }

  if (persisted.participants.length !== 1) {
    throw new Error(`Expected 1 participant, found ${persisted.participants.length}.`);
  }

  if (persisted.events.length !== 1) {
    throw new Error(`Expected 1 event, found ${persisted.events.length}.`);
  }

  if (persisted.evidence.length !== 1) {
    throw new Error(`Expected 1 evidence record, found ${persisted.evidence.length}.`);
  }

  if (!persisted.investigation) {
    throw new Error('Expected investigation relation to exist.');
  }

  if (persisted.events[0].metadata?.toString() === undefined) {
    throw new Error('Event metadata was not persisted.');
  }

  console.log('Relation graph verified.');

  console.log('\nDeleting test incident...');

  await prisma.incident.delete({
    where: {
      id: incident.id,
    },
  });

  console.log('Incident deleted.');

  console.log('\nVerifying cascade deletion...');

  const participantCount = await prisma.incidentParticipant.count({
    where: {
      id: participant.id,
    },
  });

  const eventCount = await prisma.incidentEvent.count({
    where: {
      id: event.id,
    },
  });

  const evidenceCount = await prisma.evidence.count({
    where: {
      id: evidence.id,
    },
  });

  const investigationCount = await prisma.investigation.count({
    where: {
      id: investigation.id,
    },
  });

  if (participantCount !== 0) {
    throw new Error('Participant cascade deletion failed.');
  }

  if (eventCount !== 0) {
    throw new Error('Event cascade deletion failed.');
  }

  if (evidenceCount !== 0) {
    throw new Error('Evidence cascade deletion failed.');
  }

  if (investigationCount !== 0) {
    throw new Error('Investigation cascade deletion failed.');
  }

  console.log('Cascade deletion verified.');

  console.log('\n===== PERSISTENCE SMOKE TEST PASSED =====');
}

main()
  .catch((error) => {
    console.error('\n===== PERSISTENCE SMOKE TEST FAILED =====');
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
